spring.application.name=fraud-detection-backend
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/frauddb}
spring.datasource.username=${DATABASE_USER:frauduser}
spring.datasource.password=${DATABASE_PASSWORD:fraudpass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
server.port=${PORT:8080}

anomaly.zscore.threshold=2.5
anomaly.velocity.max-transactions-per-minute=5
anomaly.amount.max-single-transaction=9500.00
anomaly.geography.suspicious-countries=NG,RU,KP,IR

cors.allowed-origins=${CORS_ORIGINS:*}